### ISSUE TITLE
Sign & send transactions

### ISSUE THREAD

**Issue by 0mkara** [ethential/wallet#2]
- [x] sign a scanned transaction
- [x] send signed transaction

**Comment by Ayanrocks** [comment]
Wallet Backend ->

- Create a server to 
   - Get GasEstimate, nonce from ethereum grpc api
   - Deploy to the specified Testnet

**Comment by 0mkara** [comment]
## The following information should be available for the user in a user-friendly manner
- [ ] how much gas is used for a transaction
- [ ] how much ether is sent with the transaction
- [ ] to which address this transaction is sent
- [ ] transaction history of the account from etherscan

**Comment by Ayanrocks** [comment]
#5

**Comment by Ayanrocks** [comment]
> * [x]  sign a scanned transaction
> * [x]  send signed transaction

Complete in #7
